Lang_SChinese fully updated:)
Lotus-AU/Languages pull request #5
Opened 2024-11-10 18:07 UTC by FollowTheFate

:)))))) I never use this before

2024-11-18 22:55 UTC, discus-sions commented
That is the only issue I see.

2024-11-19 14:55 UTC, discus-sions requested changes

2024-11-19 14:55 UTC, discus-sions commented on lang_SChinese.yaml
> +      Name: Impostors
Impostors too.

2024-11-19 14:55 UTC, discus-sions commented on lang_SChinese.yaml
> +      Name: Madmates
Madmates too.

2024-11-19 14:57 UTC, FollowTheFate commented on lang_SChinese.yaml
> +      Name: Crewmates
Sorry!I didn't saw these:((

2024-11-19 14:57 UTC, FollowTheFate commented on lang_SChinese.yaml
> +      Name: Impostors
I will fix them:(((((

2024-11-19 15:06 UTC, FollowTheFate commented
I hope there are no other issues:(

2024-11-19 15:32 UTC, discus-sions approved these changes
Thanks!

2024-11-29 00:22 UTC, merged